# Generated by Django 6.0.1 on 2026-02-20 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(default='Kerala', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('forecast_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyDiseaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('fever_op_cases', models.IntegerField(default=0)),
                ('fever_ip_cases', models.IntegerField(default=0)),
                ('chikungunya_suspected', models.IntegerField(default=0)),
                ('chikungunya_confirmed', models.IntegerField(default=0)),
                ('chikungunya_deaths', models.IntegerField(default=0)),
                ('dengue_suspected', models.IntegerField(default=0)),
                ('dengue_confirmed', models.IntegerField(default=0)),
                ('dengue_deaths', models.IntegerField(default=0)),
                ('lepto_suspected', models.IntegerField(default=0)),
                ('lepto_confirmed', models.IntegerField(default=0)),
                ('lepto_deaths', models.IntegerField(default=0)),
                ('add_cases', models.IntegerField(default=0)),
                ('chickenpox_cases', models.IntegerField(default=0)),
                ('hepatitis_a_cases', models.IntegerField(default=0)),
                ('hepatitis_b_cases', models.IntegerField(default=0)),
                ('cholera_suspected', models.IntegerField(default=0)),
                ('cholera_confirmed', models.IntegerField(default=0)),
                ('je_suspected', models.IntegerField(default=0)),
                ('je_confirmed', models.IntegerField(default=0)),
                ('malaria_imported', models.IntegerField(default=0)),
                ('malaria_indigenous', models.IntegerField(default=0)),
                ('typhoid_cases', models.IntegerField(default=0)),
                ('h1n1_cases', models.IntegerField(default=0)),
                ('measles_cases', models.IntegerField(default=0)),
                ('scrub_typhus_cases', models.IntegerField(default=0)),
                ('diphtheria_cases', models.IntegerField(default=0)),
                ('amebic_meningoencephalitis_cases', models.IntegerField(default=0)),
                ('nipah_cases', models.IntegerField(default=0)),
                ('shigella_cases', models.IntegerField(default=0)),
                ('west_nile_fever_cases', models.IntegerField(default=0)),
                ('monkeypox_cases', models.IntegerField(default=0)),
                ('covid19_cases', models.IntegerField(default=0)),
                ('covid19_deaths', models.IntegerField(default=0)),
                ('rabies_cases', models.IntegerField(default=0)),
                ('influenza_cases', models.IntegerField(default=0)),
                ('climate_rainfall_mm', models.FloatField(blank=True, null=True)),
                ('climate_avg_temp_c', models.FloatField(blank=True, null=True)),
                ('climate_humidity_percent', models.FloatField(blank=True, null=True)),
                ('social_search_index_dengue', models.FloatField(blank=True, null=True)),
                ('social_search_index_fever', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Disease Record',
                'verbose_name_plural': 'Daily Disease Records',
                'ordering': ['-report_date', 'district'],
                'indexes': [models.Index(fields=['report_date', 'district'], name='surveillanc_report__ce0de3_idx')],
                'constraints': [models.UniqueConstraint(fields=('report_date', 'district'), name='unique_daily_district_record')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('researcher', 'Researcher'), ('health_authority', 'Health Authority')], default='researcher', max_length=20)),
                ('organization', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
